variables:
  SSH_PRIVATE_KEY_BASE64: ${SCALINGO_SSH_PRIVATE_KEY_BASE64}
  # Scalingo does not support Shallow copies
  GIT_DEPTH: 0
  GRIST_DOC_ID: 1234
  GRIST_URL: https://test.com
  GRIST_API_KEY: 1234

default:
  image: node:22-alpine
  interruptible: true

stages:
- ci
- deploy
- production

sast:
  stage: ci

lint:
  stage: ci
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - yarn
    - yarn lint

test:
  stage: ci
  rules:
    - if: $CI_COMMIT_TAG == null
  script:
    - yarn
    - yarn test-ci
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

deploy-staging:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - export SSH_PRIVATE_KEY=`echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d`
    - git-push git@ssh.osc-fr1.scalingo.com:survey-builder-anct-staging.git main

release-prod:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: deploy
  allow_failure: false
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
      when: manual
  script: "echo 'Creating release'"
  manual_confirmation: 'Are you sure you want to deploy to production ?'
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v1.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v1.$CI_PIPELINE_IID'
    ref: main
  environment:
    name: production

deploy-prod:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  interruptible: false 
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - export SSH_PRIVATE_KEY=`echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d`
    - git-push git@ssh.osc-secnum-fr1.scalingo.com:survey-builder-anct-prod.git main

include:
  - template: Security/SAST.gitlab-ci.yml

