apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: app
spec:
  encryptedData:
    GRIST_API_KEY: AgDU5wNCxI0iWJ+O+xUYtderxtdcdmKQCahgvbynLwFMAUjuQR42pcV/UoEIRnwrIp4o0FrUZFRxbPTjozc7lMZQcSZroI/7NKySs2v0tBNFF8JthkC20YAHF/zTvyTOFKIJSX4tN9LPYcDEh5Qoooljz+JXldsVQbp9mn1Yg+PzTLLEeo3iiD5r1t/WTMPYMW+2SYCLKARYdmDDFIc6ytGnpGS7F17xoSFPF07l4D7nde1Necxyjh0yUWz8arZ2IVc3n1AaXV+76GpppJGyI/by67SbubI18Ewwchyfu04D/llgjFwUW3k/+HHTL1wIKpGif5cwxbGHq0x2NrcknmZL2OOc1ybZIgE6ldl3Bi4vfNBUcU+VkBmXu2j5w4U5KbFrSmxiGm8j6tNzzh0UTcctiujXxhEKgMV9lKJx4OeUfP6gkw9EcycbLJqO9QkxlgenkeQB6jtp1thFXUxhxSx/Xh/0OWFjCSzft51Ae44e+KtOIbvPhpt1QWeADwa4GoSP7pWc1snVhCr/Tr5qyGg1a1AfR8XI1nDBAe4yp5fs6CvnRuuC+32ZhNwdO3h2mIViqenmlgxDUzh69Sf3rF3k/m6hCzA50iCRNGbZxJaGM7fmstU709jtHWfsZHo7+U7dojBNrdv2Awac00blsgcsq+VjRe2htUjUVuoHsyg7tzjHXXmOkZbGRH4u2rrjnEuWagPxVWuofvw1cZROEbCol32wO5EuIGKDhIBzawWz7E85eCyo2UHL
    GRIST_DOC_ID: AgA0h4cgK47PVp3z2krpbXRAXkMu43ckQx33qd8BQnPTx0B8xnSY3qIXTdO1izlLSEARDtzHVFQ01iKzMPwRzTSyaY2yKJfPbLSM35AXxKopekPzxGG01mdHS9XncNqZF/9R0D/WTC1lOCojvnqKjJlNkXNSNjLtu7UqL9K633OSagupPQbnEGx5l5alRd+SteJtKXvYDQCKWmrZpoo8l61WWSRwLvQ/Ia1uXSdJGkrs8sJ9lzTCnuiilfeWqFteJa/4kWWHZ4lPsqFNquyX/OXJ1Lap/lANZnI8b8h6Jdv5WhOCkB16k4dojVlqlssWlVL1PZQgZRZfysjEzof+JjRjn7QhvDAFm7DgxXTNLBHhb6cycUYs19EaaapRkCmNpVi8P/XWvll+J/BPhdd33dKJPaymZkcfALWaflW8Rg1xz0ju1XwRdl11AV5EZWxex4UUOVj8NMRyFn4YvYYOaLZDqXl5aVPIUjhPI6qNvch54Kr52QF9Nss4/aW+RWYGPblSIIXIO2qmp2X9CgJSecIVB5jofMfOPyAB47OYIaxVP9e2YQ+BZIlSQjGLPq7SAhHiQG9+Uk8d09bkzfahqfeYnyp6eCQhj0jhAwsfAF7cpOsyTChxCEoqJuNjVZmkFWsfuEQipKYCfJHnStfKut7YcYnlwxY+fU/CGbqBSw/PAKAvoXK74e5zoehU0k42nTTdEZBJUPHiw8xhoOXH/6i2XB7AMgix
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: app
    type: Opaque
