app:
  probesPath: /healthz
  containerPort: 3000
  ~needs: [build-app]
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self' https://*.gouv.fr; font-src 'self'; img-src 'self'; prefetch-src 'self' https://*.gouv.fr; script-src 'self' https://*.gouv.fr; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'";
        more_set_headers "X-Frame-Options: deny";
        more_set_headers "X-XSS-Protection: 1; mode=block";
        more_set_headers "X-Content-Type-Options: nosniff";

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          GRIST_URL: "example.org"
          GIRST_DOC_ID: "3"
        secrets:
          sentry_auth_token:
            secretName: sentry
            secretKey: SENTRY_AUTH_TOKEN
          grist_api_key:
            secretName: app
            secretKey: GRIST_API_KEY
          grist_doc_id:
            secretName: app
            secretKey: GRIST_DOC_ID
