app:
  ~needs: [build-app]
  probesPath: /
  containerPort: 3000
  envFrom:
    - secretRef:
        name: app
    - configMapRef:
        name: app

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          GRIST_URL: "example.org"
          GIRST_DOC_ID: "3"
        secrets:
          sentry_auth_token:
            secretName: sentry
            secretKey: SENTRY_AUTH_TOKEN
          grist_api_key:
            secretName: app
            secretKey: GRIST_API_KEY
          grist_doc_id:
            secretName: app
            secretKey: GRIST_DOC_ID
